
env_args:
    # env: 'TicTacToe'
    # env: 'Geister'
    # env: 'HungryGeese'
    # env: 'handyrl.envs.parallel_tictactoe'  # specify by path
    env: 'simpletask'
    param:
        depth: 4
        hyperplane_n: 1
        treasure: [[3, 2]]
        set_reward: 1
        start_random: True
        pomdp_setting:
            pom_bool: False
            pom_state: [1, 1]

train_args:
    turn_based_training: False
    observation: False
    gamma: 0.9
    forward_steps: 16
    burn_in_steps: 0  # for RNNs
    compress_steps: 4
    entropy_regularization: 1.0e-1
    entropy_regularization_decay: 0.1
    update_episodes: 200
    batch_size: 256
    minimum_episodes: 10000
    maximum_episodes: 100000
    epochs: 100
    num_batchers: 2
    eval_rate: 0.1
    worker:
        num_parallel: 1
    lambda: 0.7
    policy_target: 'TD' # 'UPGO' 'VTRACE' 'TD' 'MC'
    value_target: 'TD' # 'VTRACE' 'TD' 'MC'
    eval:
        opponent: ['random']
    seed: 0
    restart_epoch: 0


worker_args:
    server_address: ''
    num_parallel: 8
